runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/.*
  script: main.app
  login: admin

- url: /clear/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest

